language: python
cache:
  - pip
matrix:
    allow_failures:
      - os: osx
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py27
install:
  - python setup.py develop
  - pip install -e .

script:
  - rm -f coverage.xml
  - nosetests -sv --cover-xml-file=coverage.xml ./tests/
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml




